# Guided Project: Finding the Best Markets to Advertise In

Let's assume that we're working for an an e-learning company that offers courses on programming. Most of our courses are on web and mobile development, but we also cover many other domains, like data science, game development, etc. We want to promote our product and we'd like to invest some money in advertisement. Our goal in this project is to find out the two best markets to advertise our product in.

To reach our goal, we could organize surveys for a couple of different markets to find out which would the best choices for advertising. This is very costly, however, and it's a good call to explore cheaper options first.

We can try to search existing data that might be relevant for our purpose. One good candidate is the data from [freeCodeCamp's 2017 New Coder Survey. freeCodeCamp](https://www.freecodecamp.org/news/we-asked-20-000-people-who-they-are-and-how-theyre-learning-to-code-fff5d668969/) is a free e-learning platform that offers courses on web development. Because they run [a popular Medium publication](https://www.freecodecamp.org/news/) (over 400,000 followers), their survey attracted new coders with varying interests (not only web development), which is ideal for the purpose of our analysis.

The survey data is publicly available in this [GitHub repository](https://github.com/freeCodeCamp/2017-new-coder-survey).

In [8]:
## read data
import pandas as pd

data=pd.read_csv('2017-fCC-New-Coders-Survey-Data.csv', low_memory=False)

data.head(10)

            

Age  AttendedBootcamp  BootcampFinish  BootcampLoanYesNo BootcampName  \
0  27.0               0.0             NaN                NaN          NaN   
1  34.0               0.0             NaN                NaN          NaN   
2  21.0               0.0             NaN                NaN          NaN   
3  26.0               0.0             NaN                NaN          NaN   
4  20.0               0.0             NaN                NaN          NaN   
5  28.0               0.0             NaN                NaN          NaN   
6  29.0               0.0             NaN                NaN          NaN   
7  29.0               0.0             NaN                NaN          NaN   
8  23.0               0.0             NaN                NaN          NaN   
9  24.0               0.0             NaN                NaN          NaN   

   BootcampRecommend  ChildrenNumber                 CityPopulation  \
0                NaN             NaN            more than 1 million   
1                NaN             NaN              less than 100,000   
2                NaN             NaN            more than 1 million   
3                NaN             NaN  between 100,000 and 1 million   
4                NaN             NaN  between 100,000 and 1 million   
5                NaN             NaN              less than 100,000   
6                NaN             NaN  between 100,000 and 1 million   
7                NaN             NaN  between 100,000 and 1 million   
8                NaN             NaN              less than 100,000   
9                NaN             NaN            more than 1 million   

   CodeEventConferences  CodeEventDjangoGirls  ...  YouTubeFCC  \
0                   NaN                   NaN  ...         NaN   
1                   NaN                   NaN  ...         1.0   
2                   NaN                   NaN  ...         NaN   
3                   NaN                   NaN  ...         1.0   
4                   NaN                   NaN  ...         NaN   
5                   NaN                   NaN  ...         NaN   
6                   1.0                   NaN  ...         NaN   
7                   NaN                   NaN  ...         1.0   
8                   NaN                   NaN  ...         NaN   
9                   1.0                   NaN  ...         1.0   

   YouTubeFunFunFunction  YouTubeGoogleDev  YouTubeLearnCode  \
0                    NaN               NaN               NaN   
1                    NaN               NaN               NaN   
2                    NaN               NaN               1.0   
3                    1.0               NaN               NaN   
4                    NaN               NaN               NaN   
5                    NaN               NaN               NaN   
6                    NaN               NaN               NaN   
7                    1.0               NaN               NaN   
8                    NaN               NaN               NaN   
9                    1.0               NaN               1.0   

   YouTubeLevelUpTuts  YouTubeMIT  YouTubeMozillaHacks         YouTubeOther  \
0                 NaN         NaN                  NaN                  NaN   
1                 NaN         NaN                  NaN                  NaN   
2                 1.0         NaN                  NaN                  NaN   
3                 1.0         NaN                  NaN                  NaN   
4                 NaN         NaN                  NaN                  NaN   
5                 NaN         NaN                  NaN  CodingEntrepreneurs   
6                 NaN         NaN                  NaN                  NaN   
7                 NaN         NaN                  NaN                  NaN   
8                 NaN         NaN                  NaN                  NaN   
9                 1.0         1.0                  NaN                  NaN   

   YouTubeSimplilearn  YouTubeTheNewBoston  
0                 NaN      

In [9]:
print(data.shape)

(18175, 136)


In [10]:
data.columns

Index(['Age', 'AttendedBootcamp', 'BootcampFinish', 'BootcampLoanYesNo',
       'BootcampName', 'BootcampRecommend', 'ChildrenNumber', 'CityPopulation',
       'CodeEventConferences', 'CodeEventDjangoGirls',
       ...
       'YouTubeFCC', 'YouTubeFunFunFunction', 'YouTubeGoogleDev',
       'YouTubeLearnCode', 'YouTubeLevelUpTuts', 'YouTubeMIT',
       'YouTubeMozillaHacks', 'YouTubeOther', 'YouTubeSimplilearn',
       'YouTubeTheNewBoston'],
      dtype='object', length=136)

We can find there are 136 columns in this survey and as we metioned before, most of the courses we offer are on web and mobile development, but we also cover many other domains, like data science, game development, etc. For the purpose of our analysis, we want to answer questions about a population of new coders that are interested in the subjects we teach. We'd like to know:

* Where are these new coders located.
* What are the locations with the greatest number of new coders.
* How much money new coders are willing to spend on learning.

Before starting to analyze the sample data we have, we need to clarify whether it's representative for our population of interest and it has the right categories of people for our purpose.

## Initial Data Exploration
According to initial exploration data, we find that The `JobRoleInterest` column describes for every participant the role(s) they'd be interested in working. So, let's generate this column distribution to determine whether this data is relevant.


In [23]:
# Frequency distribution table for 'JobRoleInterest'
data['JobRoleInterest'].value_counts(normalize=True).sort_values(ascending=False)*100

Full-Stack Web Developer                                                                                                                                              11.770595
  Front-End Web Developer                                                                                                                                              6.435927
  Data Scientist                                                                                                                                                       2.173913
Back-End Web Developer                                                                                                                                                 2.030892
  Mobile Developer                                                                                                                                                     1.673341
                                                                                                                        


The information in the table above is quite granular, but from a quick scan it looks like:

* A lot of people are interested in web development (full-stack web development, front-end web development and back-end web development).
* A few people are interested in mobile development.
* A few people are interested in domains other than web and mobile development.

It's also interesting to note that many respondents are interested in more than one subject. It'd be useful to get a better picture of how many people are interested in a single subject and how many have mixed interests. Consequently, in the next code block, we'll:

* Split each string in the `JobRoleInterest` column to find the number of options for each participant.
* We'll first drop the null values because we can't split Nan values.
* Generate a frequency table for the variable describing the number of options.

In [36]:
# Split each string in the 'JobRoleInterest' column
interests_no_nulls=data['JobRoleInterest'].dropna()
interests_split=interests_no_nulls.str.split(',')

# Frequency table for the var describing the number of options
num_of_options=interests_split.apply(lambda x: len(x))
num_of_options.value_counts(normalize= True)*100

1     31.650458
3     15.889588
4     15.217391
5     12.042334
2     10.883867
6      6.721968
7      3.861556
8      1.759153
9      0.986842
10     0.471968
12     0.300343
11     0.185927
13     0.028604
Name: JobRoleInterest, dtype: float64

It turns out that only 31.7% of the participants have a clear idea about what programming niche they'd like to work in, while the vast majority of students have mixed interests. But given that we offer courses on various subjects, the fact that new coders have mixed interest might be actually good for us.

The focus of our courses is on web and mobile development, so let's find out how many respondents chose at least one of these two options.

In [37]:
# Frequency table
web_or_mobile = interests_no_nulls.str.contains(
    'Web Developer|Mobile Developer') # returns an array of booleans
freq_table = web_or_mobile.value_counts(normalize = True) * 100
print(freq_table)

True     86.241419
False    13.758581
Name: JobRoleInterest, dtype: float64


In [39]:
# Graph for the frequency table above
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
freq_table.plot.bar()
plt.title('Most Participants are Interested in \nWeb or Mobile Development',
          y = 1.08) # y pads the title upward
plt.ylabel('Percentage', fontsize = 12)
plt.xticks([0,1],['Web or mobile\ndevelopment', 'Other subject'],
           rotation = 0) # the initial xtick labels were True and False
plt.ylim([0,100])
plt.show()

It turns out that most people in this survey (roughly 86%) are interested in either web or mobile development. These figures offer us a strong reason to consider this sample representative for our population of interest. We want to advertise our courses to people interested in all sorts of programming niches but mostly web and mobile development.

Now we need to figure out what are the best markets to invest money in for advertising our courses. We'd like to know:

* Where are these new coders located.
* What are the locations with the greatest number of new coders.
* How much money new coders are willing to spend on learning.

## New Coders Location
Let's begin with finding out where these new coders are located, and what are the densities (how many new coders there are) for each location. This should be a good start for finding out the best two markets to run our ads campaign in.

The data set provides information about the location of each participant at a country level. We can think of each country as an individual market, so we can frame our goal as finding the two best countries to advertise in.

We can start by examining the frequency distribution table of the `CountryLive` columns, which describes what country each participant lives in (not their origin country). We'll only consider those participants who answered what role(s) they're interested in, to make sure we work with a representative sample.

In [48]:
# Isolate the participants that answered what role they'd be interested in
data_interested=data[data['JobRoleInterest'].notnull()].copy()

# Frequency tables with absolute and relative frequencies
ab_f=data_interested['CountryLive'].value_counts()
re_f=data_interested['CountryLive'].value_counts(normalize=True)*100

# Display the frequency tables in a more readable format

location=pd.DataFrame(data={'Absolute frequency':ab_f,
                            'Percentage': re_f}
                     )
location.head(10)

Absolute frequency  Percentage
United States of America                3125   45.700497
India                                    528    7.721556
United Kingdom                           315    4.606610
Canada                                   260    3.802281
Poland                                   131    1.915765
Brazil                                   129    1.886517
Germany                                  125    1.828020
Australia                                112    1.637906
Russia                                   102    1.491664
Ukraine                                   89    1.301550

45.7% of our potential customers are located in the US, and this definitely seems like the most interesting market. India has the second customer density, but it's just 7.7%, which is not too far from the United Kingdom (4.6%) or Canada (3.8%).

This is useful information, but we need to go more in depth than this and figure out how much money people are actually willing to spend on learning. Advertising in high-density markets where most people are only willing to learn for free is extremely unlikely to be profitable for us.

## Average Monthly Spend

Previously, we found useful information about the location of new coders, and what are the countries where new coders live, but we need to go more in depth with our analysis before taking a decision. We can continue by figuring out how much money new coders are actually willing to spend on learning. Advertising within markets where most people are only willing to learn for free is extremely unlikely to be profitable for us.

The `MoneyForLearning` column describes in American dollars the amount of money spent by participants from the moment they started coding until the moment they completed the survey. Our company sells subscriptions at a price of $59 per month, and for this reason we're interested in finding out how much money each student spends per month.

It also seems like a good idea to narrow down our analysis to only four countries: the US, India, the United Kingdom, and Canada. Two reasons for this decision are:

* These are the countries having the highest absolute frequencies in our sample, which means we have a decent amount of data for each.
* Our courses are written in English, and English is an official language in all these four countries. The more people that know English, the better our chances to target the right people with our ads.